name: Test application

on:
    pull_request:
    push:
        branches:
            - '*.x'

jobs:
    phpunit-doctrine_dbal:
        name: 'PHP ${{ matrix.php-version }} Doctrine DBAL ${{ matrix.jackalope-version }} ${{ matrix.dependencies }} Symfony ${{ matrix.symfony-version }}'

        runs-on: ubuntu-20.04

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: phpcr_odm_tests
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        strategy:
            fail-fast: false

            matrix:
                php-version:
                    - '8.1'
                    - '8.2'
                    - '8.3'
                dependencies: [highest]
                symfony-version: ['*']
                jackalope-version: ['1.*']
                include:
                  - php-version: '8.1'
                    dependencies: lowest
                    symfony-version: '*'
                  - php-version: '8.1'
                    dependencies: highest
                    symfony-version: '5.4.*'
                  - php-version: '8.2'
                    dependencies: highest
                    symfony-version: '6.*'
                  - php-version: '8.3'
                    dependencies: highest
                    symfony-version: '7.*'
                    jackalope-version: '2.*'
                    php-bench: true

        steps:
            - name: Checkout project
              uses: actions/checkout@v3

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: 'composer:v2, flex'

            - name: Symfony version
              if: matrix.symfony-version != '*'
              run: composer config extra.symfony.require ${{ matrix.symfony-version }}

            - name: Install Jackalope Doctrine DBAL transport
              run: composer require jackalope/jackalope-doctrine-dbal:"${{ matrix.jackalope-version }}" --no-update

            - name: Install PHPBench
              if: matrix.php-bench == true
              run: composer require phpbench/phpbench:"^1.0" --no-update

            - name: Install dependencies with Composer
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: ${{ matrix.dependencies }}
                  composer-options: --prefer-dist

            - name: Cache Jackrabbit
              id: cache-jackrabbit
              uses: actions/cache@v3
              with:
                path: vendor/jackalope/jackalope-jackrabbit/bin/jackrabbit-standalone-*
                key: jackrabbit

            - name: Run configuration script
              run: ./tests/script_doctrine_dbal.sh

            - name: Execute test cases
              run: vendor/bin/phpunit -c tests/phpunit_doctrine_dbal.xml.dist

            - name: Execute PHPBench
              if: matrix.php-bench == true
              run: vendor/bin/phpbench run --report=all
              env:
                  TRANSPORT: doctrine_dbal

    phpunit-jackrabbit:
        name: 'PHP ${{ matrix.php-version }} Jackrabbit ${{ matrix.jackalope-version }} ${{ matrix.dependencies }} Symfony ${{ matrix.symfony-version }}'

        runs-on: ubuntu-20.04

        strategy:
            fail-fast: false

            matrix:
                php-version:
                    - '8.1'
                    - '8.2'
                    - '8.3'
                dependencies: [highest]
                symfony-version: ['*']
                jackalope-version: ['1.*']
                include:
                  - php-version: '8.1'
                    dependencies: lowest
                    symfony-version: '*'
                  - php-version: '8.1'
                    dependencies: highest
                    symfony-version: 5.4.*
                  - php-version: '8.2'
                    dependencies: highest
                    symfony-version: '6.*'
                  - php-version: '8.3'
                    dependencies: highest
                    symfony-version: '7.*'
                    jackalope-version: '2.*'
                    php-bench: true

        steps:
            - name: Checkout project
              uses: actions/checkout@v3

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: 'composer:v2, flex'

            - name: Symfony version
              if: matrix.symfony-version != '*'
              run: composer config extra.symfony.require ${{ matrix.symfony-version }}

            - name: Install and configure Java
              uses: actions/setup-java@v3
              with:
                  distribution: temurin
                  java-version: '8'

            - name: Install Jackalope Jackrabbit
              run: composer require jackalope/jackalope-jackrabbit:"${{ matrix.jackalope-version }}" --no-update

            - name: Install PHPBench
              if: matrix.php-bench == true
              run: composer require phpbench/phpbench:"^1.0" --no-update

            - name: Install dependencies with Composer
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: ${{ matrix.dependencies }}
                  composer-options: --prefer-dist

            - name: Run configuration script
              run: ./tests/script_jackrabbit.sh

            - name: Execute test cases
              run: vendor/bin/phpunit -c tests/phpunit_jackrabbit.xml.dist

            - name: Execute PHPBench
              if: matrix.php-bench == true
              run: vendor/bin/phpbench run --report=all
              env:
                  TRANSPORT: jackrabbit
